version: '3'

services:
  database:
    image: mariadb
    container_name: ${NAME}_db
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: "${MYSQL_DATABASE}"
      MARIADB_USER: "${MYSQL_USERNAME}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}" 
    networks:
      - lan
    volumes: 
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin 
    container_name: ${NAME}_pma
    restart: unless-stopped
    environment: 
      PMA_ABSOLUTE_URI: https://${NAME}.jrcan.dev/phpmyadmin
      PMA_HOST: ${NAME}_db
      UPLOAD_LIMIT: 128M
    labels:
      - traefik.enable=true  
      - traefik.http.routers.pma_${NAME}.entrypoints=websecure
      - traefik.http.routers.pma_${NAME}.rule=Host(`${NAME}.jrcan.dev`) && PathPrefix(`/phpmyadmin/`)
      - traefik.http.middlewares.pmapathstrip_${NAME}.stripprefix.prefixes=/phpmyadmin
      - traefik.http.routers.pma_${NAME}.middlewares=pmapathstrip_${NAME}@docker
      - traefik.http.routers.pma_${NAME}.tls=true
      - traefik.http.routers.pma_${NAME}.tls.certresolver=myresolver
    volumes:
      - /sessions
    networks:
      - web      
      - lan

  app:
    image: bitnami/laravel:latest
    container_name: ${NAME}
    networks:
      - lan
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.entryPoints=websecure 
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}.tls=true  
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver
    restart: always
    environment:
      LARAVEL_DATABASE_HOST: ${NAME}_db
      LARAVEL_DATABASE_NAME: "${MYSQL_DATABASE}"
      LARAVEL_DATABASE_USER: "${MYSQL_USERNAME}"
      LARAVEL_DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./src:/app 

  olivetin:
    image: olivetin/olivetin:latest
    container_name: ${NAME}_olivetin
    restart: unless-stopped
    environment:
      OLIVETIN_PORT: 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.olivetin_${NAME}.entrypoints=websecure
      - traefik.http.routers.olivetin_${NAME}.rule=Host(`${NAME}.jrcan.dev`) && PathPrefix(`/olivetin/`)
      - traefik.http.middlewares.olivetinpathstrip_${NAME}.stripprefix.prefixes=/olivetin
      - traefik.http.routers.olivetin_${NAME}.middlewares=olivetinpathstrip_${NAME}@docker
      - traefik.http.routers.olivetin_${NAME}.tls=true
      - traefik.http.routers.olivetin_${NAME}.tls.certresolver=myresolver
    ports:
      - "8000:80"
    networks:
      - web
      - lan

volumes:
  db:

networks:
  web:
    external: true
  lan:
    external: false
    name: lan_${NAME}
